### ISSUE TITLE
Limitation on chunksize

### ISSUE THREAD

**Issue by sapoluri** [t-mat/lz4mt#39]
When running benchmark the chunksize doesn't seem limited but when using lz4mtcompress, it initializes the maximum block size to 1 << (8 + 2 * (value between 4 to 7)). So the size of the chunk is limited to 44 bytes. That seems arbitrary and unnecessary.

May be I didn't completely understand the implementation but to me, it seems wrong.

**Comment by t-mat** [comment]
I'm not sure what you're trying to point out.  So I'm really sorry if I'm misunderstanding your question.

> 1 << (8 + 2 * (value between 4 to 7)). So the size of the chunk is limited to 44 bytes.

I think you mean "`4Mi` bytes" instead of "`44` bytes".  But for just in case, please refer the following example code

```C++
// https://ideone.com/w9UQzD
#include <stdio.h>
int main() {
   for(int i = 4; i <= 7; ++i) {
      int x = 1 << (8 + (2 * i));
      printf("i = %d, x=%d\n", i, x);
   }
}
```

> That seems arbitrary and unnecessary.

Since "LZ4 Frame Format"[1] document strictly specify possible block (chunk) maximum size as one of { 64Ki, 256Ki, 1Mi, 4Mi }, it's required and this part of code is just following the spec.

[1] LZ4 Frame Format, https://github.com/lz4/lz4/blob/master/doc/lz4_Frame_format.md

**Comment by sapoluri** [comment]
Thank you for clarifying! 

I read it as (8 + (2 * i)) << 1 instead of 1 << (8 + (2*i)). I apologize.

Appreciate your patience in explaining it.
